description =      "Far far away, behind the word mountains..."

job_categories =   ["finance",
                    "office",
                    "art",
                    "science",
                    "retail",
                    "software",
                    "media",
                    "web",
                    "government",
                    "legal",
                    "marketing",
                    "service"]

dummy_jobs =       ["Bailiff",
                    "Horticulturalist",
                    "Radio presenter",
                    "Dressmaker",
                    "Social worker",
                    "Anthropologist",
                    "Car dealer",
                    "Tour guide",
                    "Speech therapist",
                    "Bookmaker",
                    "Comedian",
                    "Garden designer",
                    "Plumber"]

stuff_categories = ["antiques",
                    "appliances",
                    "arts+crafts",
                    "atv+utv+sno",
                    "auto parts",
                    "baby+kid",
                    "barter",
                    "beauty+hlth",
                    "bikes",
                    "boats",
                    "books",
                    "business",
                    "cars+trucks",
                    "cds+dvd+vhs",
                    "cell phones",
                    "clothes+acc",
                    "collectibles",
                    "computers",
                    "electronics",
                    "farm+garden",
                    "free",
                    "furniture",
                    "garage sale",
                    "general",
                    "heavy equip",
                    "household",
                    "jewelry",
                    "materials",
                    "motorcycles",
                    "music instr",
                    "photo+video",
                    "rvs+camp",
                    "sporting",
                    "tickets",
                    "tools",
                    "toys+games",
                    "trailers",
                    "video gaming",
                    "wanted"]

dummy_stuff =      ["Dinosaur bookends, handmade",
                    "Edmund Scientific Astroscan Telescope",
                    "Fish",
                    "Meter Valve Box",
                    "Parrot Bird Cage ",
                    "Hangar Doors",
                    "Pink, red and white felt flower wreath",
                    "Colorfully rustic, wallhanging candle holders",
                    "Gold painted, rustic wood with mason jar vase",
                    "Three little kittens, no mittens",
                    "Liberty Gun Safe - Presidential Series 50",
                    "Tow Car Shield"]

space_categories = ["apartments",
                    "homes",
                    "office",
                    "parking",
                    "for sale",
                    "rooms",
                    "vacation rentals",
                    "sublets"]

dummy_space =      ["Hit the bulls-eye",
                    "Parking Space",
                    "Newly Renovated, Stainless Steel",
                    "Need Extra Space? Dry, secure storage!",
                    "Don't Gamble on Your Next Place! ",
                    "Corner Unit , Extra Storage, W/D",
                    "Creative Office Space in Central Downtown Portland"]
