description =      ("Far far away, behind the word mountains, "
                    "far from the countries Vokalia and Consonantia, "
                    "there live the blind texts. Separated they live in "
                    "Bookmarksgrove right at the coast of the Semantics, "
                    "a large language ocean. A small river named Duden "
                    "flows by their place and supplies it with the "
                    "necessary regelialia.")

job_categories =   ["finance",
                    "office",
                    "art",
                    "science",
                    "retail",
                    "software",
                    "media",
                    "web",
                    "government",
                    "legal",
                    "marketing",
                    "service"]

dummy_jobs =       ["Bailiff",
                    "Horticulturalist",
                    "Radio presenter",
                    "Dressmaker",
                    "Social worker",
                    "Anthropologist",
                    "Car dealer",
                    "Tour guide",
                    "Speech therapist",
                    "Bookmaker",
                    "Comedian",
                    "Garden designer",
                    "Plumber"]

stuff_categories = ["antiques",
                    "appliances",
                    "arts+crafts",
                    "atv+utv+sno",
                    "auto parts",
                    "baby+kid",
                    "barter",
                    "beauty+hlth",
                    "bikes",
                    "boats",
                    "books",
                    "business",
                    "cars+trucks",
                    "cds+dvd+vhs",
                    "cell phones",
                    "clothes+acc",
                    "collectibles",
                    "computers",
                    "electronics",
                    "farm+garden",
                    "free",
                    "furniture",
                    "garage sale",
                    "general",
                    "heavy equip",
                    "household",
                    "jewelry",
                    "materials",
                    "motorcycles",
                    "music instr",
                    "photo+video",
                    "rvs+camp",
                    "sporting",
                    "tickets",
                    "tools",
                    "toys+games",
                    "trailers",
                    "video gaming",
                    "wanted"]

dummy_stuff =      ["Dinosaur bookends, handmade",
                    "Edmund Scientific Astroscan Telescope",
                    "Fish",
                    "Meter Valve Box",
                    "Parrot Bird Cage ",
                    "Hangar Doors",
                    "Pink, red and white felt flower wreath",
                    "Colorfully rustic, wallhanging candle holders",
                    "Gold painted, rustic wood with mason jar vase",
                    "Three little kittens, no mittens",
                    "Liberty Gun Safe - Presidential Series 50",
                    "Tow Car Shield",
                    "Traeger BBQ+Smoker, cover, tray, 6 bags of pellets",
                    "5 Ton Fridgidaire High Efficiency Air Conditioner AC With 5 Ton Coil",
                    "Pottery Barn Lina Moroccan Pillows",
                    "3.5 Ton Fridgidaire High Efficiency Air Conditioner + W+ 3.5 Ton Coil",
                    "Pottery Barn Jewelry Box ",
                    "Creative Memories Shape Punchers",
                    "Shipping Container Cover for Storage Containers(container)",
                    "Various types of large-volume, plastic or steel containers for liquids",
                    "Rustic handmade display shelf with 'built in' planter",
                    "Rare! Converse airline + bowling bag style AND pink 'clutch'",
                    "FOR SALE PROPERTY 1.89 Acres w+Panoramic Views-Older HomeOutdoor Light Fixture, Marine Quality, Heavy Duty",
                    "Staple Pliers lot of 3",
                    "Star Wars metal spaceships",
                    "Solid Wood Picture Window Wood Picture Window - $80Fish Tank 34 Gal. With Orniments",
                    "Faded green, handmade, Welcome sign with mason jar",
                    "Garage storage cabinet cabinetsEagle Creek Cargo Switchback Plus Wheeled Luggage  $70",
                    "Coleman firepit grill $39",
                    "Full metal fidget spinners, matte black",
                    "Old tools",
                    "woodworking stuff",
                    "dabs!",
                    "Stainless steel Bird cages",
                    "Maxi cosi car seat",
                    "BioLite Wood Burning CampStove First Generation",
                    "Greek style columnar brass candle holders",
                    "Solidex 928xt VHS video tape rewinder",
                    "Vitamix 3600 blender  ",
                    "Canon MF8280CW Printer",
                    "TX RACING WHEEL XBOX  ",
                    "Balinese dancers framed watercolor painting $29",
                    "Biolight stove",
                    "Harman kardon HKTS 16BQ",
                    "Optoma Technology DH1011 Full HD DLP 3D Projector",
                    "WALKER",
                    "stuff not using",
                    "QUICKIE ELECTRIC WHEELCHAIR",
                    "Atmomixani Nemesis Mechanical Vape Mod, Atmo Dome",
                    "SERTA 3000 Perfect Sleeper king size double pillow mattress",
                    "DAKOTA MENS LARGE WATERPROOF JACKET + COAT",
                    "10 Ton Manual Log Splitter with Polls",
                    "SERTA 3000 Perfect Sleeper king size double pillow mattress",
                    "Vintage HAM Radio Set up--everything but the tower!",
                    "Aquarium Bio Filter",
                    "Garden Umbrella Stand",
                    "Polar Loop Activity Tracker Black"]

space_categories = ["apartments",
                    "homes",
                    "office",
                    "parking",
                    "for sale",
                    "rooms",
                    "vacation rentals",
                    "sublets"]

dummy_space =      ["Hit the bulls-eye & Rent here! Luxury 1 Bdrm w/ Huge Everything",
                    "Parking Space, One Block Away NW 23RD!! Available 8/1/17 & 9/1/17",
                    "Newly Renovated, Stainless Steel, New Flooring and much more",
                    "Need Extra Space? Dry, secure storage! Avail 08/01/17 Close to NW 23rd",
                    "Don't Gamble on Your Next Place! Win in This 2 Bedroom!",
                    "Corner Unit , Extra Storage, W/D, Roommate Friendly !! Pool !",
                    "Creative Office Space in Central Downtown Portland",
                    "Brand New Amenities FREE MONTH Clean & Simple MOVE NOW Tigard 97223",
                    "Just One Opportunity Left to Get 1-month Free! New Homes, New Deals",
                    "Great Room feel, hardwoods, large shower, DBL garage-3BR",
                    "Very nice 2-story house in Morning Green Neighborhood in Hillsboro!",
                    "$500 Room by Max Line/Mall 205 - Renting for 2mos ONLY",
                    "Package receiving service, 24-Hour maintenance response, Sundeck",
                    "Carport, Parking with Cover near NW 23RD $175/Mo Available 08/01/2017",
                    "Beautiful two bedroom townhome, newly renovated, community playground",
                    "Need a Summer Retreat APARTMENT AVAILABLE SOON!",
                    "Newly renovated condo right across from the beach for rent!",
                    "Contemporary, Urban 1 bedroom w/ Awesome City View! $1395",
                    "Wood-style flooring, Disability Access, Accepts Electronic Payments",
                    "Italian Porcelain Tile & Custom Wood Cabinetry in a 1x1 Apartment!",
                    "3 bed/2.5 bath Home In Portsmouth Neighborhood",
                    "Brand New 3 Bdrm Townhouse w/ High-End Finishes! Washer/Dryer Incl.!",
                    "TWO BEDROOM IN TIGARD ENJOY PLAYGROUND & POOL ",
                    "Brand New 3 Bdrm Townhouse w/ High-End Finishes! Washer/Dryer Incl.!",
                    "Office Available in Historic Building at 6th & Main",
                    "Newer 4 Bedroom Townhouse-End Unit! High End Finishes!",
                    "Retail Space near SR-500",
                    "3 Bedroom Condo",
                    "Newer 4 Bedroom Townhouse-End Unit! High End Finishes!",
                    "Very Nice Lake Oswego 2-story - includes seasonal yard care!",
                    "Beautiful Ground Floor 2 Bed 1 Bath Flat! Apply Online Today!",
                    "1 Bth. Washer / Dryer . Off Scholls Ferry by Washington sq mall",
                    "Newer 4 Bedroom Townhouse-End Unit! High End Finishes!",
                    "Call For Specials on our One Bedroom Apartment Homes!",
                    "Beautiful newly remodeled 1x1 ready for move-in, pet friendly",
                    "Room for rent in SW Portland near Barbur and Capitol hwy",
                    "PERFECT 3 BDRM HOME W/BONUS RM OPEN PLAN FRPLC PETS OK+FENCED YD",
                    "Brand New 3 Bedroom Townhouse w/ 2-Car Garage! Washer/Dryer Inc",
                    "Brand New 3 Bedroom, 2.5 Bath Townhome w/ High End Finishes!",
                    "Arbor Lodge/Overlook - Willamette Blvd Townhouse",
                    "GROUND FLOOR 1X1!!! NEW CARPET, W/D INCLUDED, CARPORT!! READY NOW!!",
                    "Lovely Spacious Tigard Home on Bull Mountain!",
                    "Fabulous 'duplex' in quiet ALAMEDA neighborhood. Nice landlady.",
                    "2 bedroom 1.5 bathroom townhouse with washer and dryer!!",
                    "Newly Remodeled 2 Bedroom 1 Bath in St. Helens, $1,500!!",
                    "Spectacular 3 bed 2.5 bath home w/ easy access to I-5",
                    "WOW WELL MANICURED AND MAINTAINED HOME",
                    "Office Best Deal In TownMove In ReadyCome And See Us",
                    "Stunning 3 bed 2.5 bath Townhome w/ easy access to HWY 26",
                    "Love the location!  Come see our new look!  Move-In Ready!",
                    "SW Portland Special"]
